### ISSUE TITLE
oss-fuzz build error for readstat-13262 artifact

### ISSUE THREAD

**Issue by YoungseokCh** [ARISE-Handong/BugOss#1]
Hello,

I am trying to build readstat-13262, however it fails with following messages:
```
src/sas/readstat_sas7bdat_read.c:603:19: error: missing terminating '"' character [-Werror,-Winvalid-pp-token]
{ fprintf(stderr, "[BugOSS] src/sas/readstat_sas7bdat_read.c:602
                  ^
src/sas/readstat_sas7bdat_read.c:603:19: error: expected expression
src/sas/readstat_sas7bdat_read.c:604:1: error: missing terminating '"' character [-Werror,-Winvalid-pp-token]
"); goto cleanup; }
```

I found that https://github.com/ARISE-Handong/BugOss/blob/05e2bbf530e61fbf2a71ae758cd66e1b038c7a95/artifacts/readstat-13262/build.sh#L21 is causing this issue because `\n` is not escaped properly in `sed` command. Is it okay to delete line 20 and line 21?

**Comment by JeewoongKim** [comment]
I changed the double quote to a single quote.

Lines 20-21 in `readstat-13262/build.sh` are related to test oracles
The lines are used only for discriminating failures.
Comment out the lines when you build for a fuzzing run
